# Generated by Django 4.2.3 on 2023-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="man", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default="iran", max_length=255),
            preserve_default=False,
        ),
    ]
