# Generated by Django 4.2.3 on 2023-07-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="Education",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.education"),
        ),
    ]
