# Generated by Django 4.2.3 on 2023-07-15 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_education_user_user_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Education",
            new_name="education",
        ),
    ]
