# Generated by Django 4.2.3 on 2023-07-15 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_education_user_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="education",
        ),
        migrations.AddField(
            model_name="education",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
